version: 2

sources:
  - name: dbt_demo
    schema: raw
    tables:
      - name: raw_calendar
        identifier: calendar

      - name: raw_listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4 
      - name: raw_reviews
        identifier: raw_reviews